

services:
  backend:
    # Construye la imagen usando el Dockerfile en el directorio actual (.)
    build: .
    # Carga las variables desde el archivo .env
    env_file:
      - .env
    # Mapea el puerto 8000 de tu PC al puerto 8000 del contenedor
    ports:
      - "8000:8000"
    # Añade esto para que Docker pueda encontrar el host de tu máquina
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mapea la carpeta local './certs' a la carpeta '/app/certs' dentro del contenedor
      - ./certs:/app/certs
      # Monta el archivo local en la ruta /app/client_secret.json del contenedor
      - ./client_secret.json:/app/client_secret.json
      # Monta la carpeta de datos LOCAL (que está dentro de backend) a /app/data
      - ./backend/data:/app/backend/data