"""Agregar roles a la relacion proyecto-usuario

Revision ID: 01582d26a5fd
Revises: e4784a95a3c9
Create Date: 2025-09-23 17:58:25.368377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01582d26a5fd'
down_revision: Union[str, Sequence[str], None] = 'e4784a95a3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyecto_usuarios', sa.Column('rol', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyecto_usuarios', 'rol')
    # ### end Alembic commands ###
