"""cabmio en batch de str a int 

Revision ID: 116b73650f09
Revises: 75b2d4a76eae
Create Date: 2025-08-13 15:36:09.378683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116b73650f09'
down_revision: Union[str, Sequence[str], None] = '75b2d4a76eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas_electronicas', 'batch',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               # Esta lógica convierte solo los valores numéricos y pone NULL en los demás
               postgresql_using="""
               CASE
                   WHEN batch ~ '^[0-9]+$' THEN batch::integer
                   ELSE NULL
               END
               """
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas_electronicas', 'batch',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
