"""Agregar Superuser y relaciones 

Revision ID: 20d2e152802b
Revises: 01582d26a5fd
Create Date: 2025-09-23 20:38:26.970823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d2e152802b'
down_revision: Union[str, Sequence[str], None] = '01582d26a5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_superuser')
    # ### end Alembic commands ###
