"""Agregar tablas Categoria y Proyecto y sus relaciones

Revision ID: 69f196f0c89a
Revises: aa82793e6258
Create Date: 2025-07-27 17:05:23.465252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69f196f0c89a'
down_revision: Union[str, Sequence[str], None] = 'aa82793e6258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.add_column('empresas', sa.Column('nombre', sa.String(), nullable=False))
    op.add_column('empresas', sa.Column('nit', sa.String(), nullable=False))
    op.create_index(op.f('ix_empresas_nit'), 'empresas', ['nit'], unique=True)
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=False)
    op.add_column('facturas_electronicas', sa.Column('msg_pdf_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('facturas_electronicas', sa.Column('batch', sa.String(), nullable=True))
    op.add_column('facturas_electronicas', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.add_column('facturas_electronicas', sa.Column('proyecto_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_facturas_electronicas_batch'), 'facturas_electronicas', ['batch'], unique=False)
    op.create_foreign_key(None, 'facturas_electronicas', 'proyectos', ['proyecto_id'], ['id'])
    op.create_foreign_key(None, 'facturas_electronicas', 'categorias', ['categoria_id'], ['id'])
    op.add_column('facturas_manuales', sa.Column('batch', sa.String(), nullable=True))
    op.add_column('facturas_manuales', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.add_column('facturas_manuales', sa.Column('proyecto_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_facturas_manuales_batch'), 'facturas_manuales', ['batch'], unique=False)
    op.create_foreign_key(None, 'facturas_manuales', 'proyectos', ['proyecto_id'], ['id'])
    op.create_foreign_key(None, 'facturas_manuales', 'categorias', ['categoria_id'], ['id'])
    op.add_column('proyectos', sa.Column('nombre', sa.String(), nullable=False))
    op.add_column('proyectos', sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False))
    op.add_column('proyectos', sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_proyectos_nombre'), 'proyectos', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proyectos_nombre'), table_name='proyectos')
    op.drop_column('proyectos', 'fecha_fin')
    op.drop_column('proyectos', 'fecha_inicio')
    op.drop_column('proyectos', 'nombre')
    op.drop_constraint(None, 'facturas_manuales', type_='foreignkey')
    op.drop_constraint(None, 'facturas_manuales', type_='foreignkey')
    op.drop_index(op.f('ix_facturas_manuales_batch'), table_name='facturas_manuales')
    op.drop_column('facturas_manuales', 'proyecto_id')
    op.drop_column('facturas_manuales', 'categoria_id')
    op.drop_column('facturas_manuales', 'batch')
    op.drop_constraint(None, 'facturas_electronicas', type_='foreignkey')
    op.drop_constraint(None, 'facturas_electronicas', type_='foreignkey')
    op.drop_index(op.f('ix_facturas_electronicas_batch'), table_name='facturas_electronicas')
    op.drop_column('facturas_electronicas', 'proyecto_id')
    op.drop_column('facturas_electronicas', 'categoria_id')
    op.drop_column('facturas_electronicas', 'batch')
    op.drop_column('facturas_electronicas', 'msg_pdf_request')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nit'), table_name='empresas')
    op.drop_column('empresas', 'nit')
    op.drop_column('empresas', 'nombre')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
