"""se actualizo unique users 

Revision ID: 6af3b3ff712d
Revises: 7431f859d1bb
Create Date: 2025-09-23 11:38:31.909519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af3b3ff712d'
down_revision: Union[str, Sequence[str], None] = '7431f859d1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    # ### end Alembic commands ###
