"""Crear tablas iniciales de facturas

Revision ID: 7373210721dc
Revises: 
Create Date: 2025-07-04 18:43:04.857248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7373210721dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas_electronicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('Nit_Beneficiario', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('detalles', sa.String(), nullable=True),
    sa.Column('n_factura', sa.Integer(), nullable=True),
    sa.Column('monto_fiscal', sa.Float(), nullable=True),
    sa.Column('nit_emisor', sa.String(), nullable=True),
    sa.Column('factura_especial', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_electronicas_id'), 'facturas_electronicas', ['id'], unique=False)
    op.create_table('facturas_manuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nit_Beneficiario', sa.String(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_manuales_id'), 'facturas_manuales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_manuales_id'), table_name='facturas_manuales')
    op.drop_table('facturas_manuales')
    op.drop_index(op.f('ix_facturas_electronicas_id'), table_name='facturas_electronicas')
    op.drop_table('facturas_electronicas')
    # ### end Alembic commands ###
