"""Agregar restriccion unique a url en factura electronica

Revision ID: 75b2d4a76eae
Revises: f028f214a0e3
Create Date: 2025-08-13 15:14:30.513703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b2d4a76eae'
down_revision: Union[str, Sequence[str], None] = 'f028f214a0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
