"""Cambio en columnas que fallaban 

Revision ID: 775eba70c541
Revises: 20d2e152802b
Create Date: 2025-09-24 22:52:17.911178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775eba70c541'
down_revision: Union[str, Sequence[str], None] = '20d2e152802b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas_electronicas', sa.Column('status', sa.String(), nullable=True))
    op.add_column('facturas_electronicas', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas_electronicas', 'complete')
    op.drop_column('facturas_electronicas', 'status')
    # ### end Alembic commands ###
