"""Cambiar columna detalles a JSONB

Revision ID: 8647430c8260
Revises: 6d272e6f65ed
Create Date: 2025-07-16 15:52:29.543902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8647430c8260'
down_revision: Union[str, Sequence[str], None] = '6d272e6f65ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas_electronicas', sa.Column('save_pdf', sa.Boolean(), nullable=True))
    op.alter_column('facturas_electronicas', 'detalles',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="NULLIF(detalles, '')::jsonb")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas_electronicas', 'detalles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('facturas_electronicas', 'save_pdf')
    # ### end Alembic commands ###
