"""agregar columnas msg de cada proceso

Revision ID: aa82793e6258
Revises: 8647430c8260
Create Date: 2025-07-17 19:36:56.554008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa82793e6258'
down_revision: Union[str, Sequence[str], None] = '8647430c8260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas_electronicas', sa.Column('msg_get_request', sa.String(), nullable=True))
    op.add_column('facturas_electronicas', sa.Column('msg_post_request', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas_electronicas', 'msg_post_request')
    op.drop_column('facturas_electronicas', 'msg_get_request')
    # ### end Alembic commands ###
