"""Configurar reglas de eliminacion en cascada para categorias y proyectos

Revision ID: ad4c982d6b73
Revises: d39b42afb17e
Create Date: 2025-07-27 17:49:28.461066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4c982d6b73'
down_revision: Union[str, Sequence[str], None] = 'd39b42afb17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('facturas_electronicas_categoria_id_fkey'), 'facturas_electronicas', type_='foreignkey')
    op.drop_constraint(op.f('facturas_electronicas_proyecto_id_fkey'), 'facturas_electronicas', type_='foreignkey')
    op.create_foreign_key(None, 'facturas_electronicas', 'proyectos', ['proyecto_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'facturas_electronicas', 'categorias', ['categoria_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('facturas_manuales_categoria_id_fkey'), 'facturas_manuales', type_='foreignkey')
    op.drop_constraint(op.f('facturas_manuales_proyecto_id_fkey'), 'facturas_manuales', type_='foreignkey')
    op.create_foreign_key(None, 'facturas_manuales', 'proyectos', ['proyecto_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'facturas_manuales', 'categorias', ['categoria_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facturas_manuales', type_='foreignkey')
    op.drop_constraint(None, 'facturas_manuales', type_='foreignkey')
    op.create_foreign_key(op.f('facturas_manuales_proyecto_id_fkey'), 'facturas_manuales', 'proyectos', ['proyecto_id'], ['id'])
    op.create_foreign_key(op.f('facturas_manuales_categoria_id_fkey'), 'facturas_manuales', 'categorias', ['categoria_id'], ['id'])
    op.drop_constraint(None, 'facturas_electronicas', type_='foreignkey')
    op.drop_constraint(None, 'facturas_electronicas', type_='foreignkey')
    op.create_foreign_key(op.f('facturas_electronicas_proyecto_id_fkey'), 'facturas_electronicas', 'proyectos', ['proyecto_id'], ['id'])
    op.create_foreign_key(op.f('facturas_electronicas_categoria_id_fkey'), 'facturas_electronicas', 'categorias', ['categoria_id'], ['id'])
    # ### end Alembic commands ###
