"""Cambiar pdf_bytes a pdf_path en facturas electronicas

Revision ID: b22e03d3bddc
Revises: 116b73650f09
Create Date: 2025-09-17 10:46:56.920932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b22e03d3bddc'
down_revision: Union[str, Sequence[str], None] = '116b73650f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas_electronicas', 'pdfIO',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas_electronicas', 'pdfIO',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
