"""Agregar columna pdf_bytes a factura_electronica y status y savepdf

Revision ID: c400935a5708
Revises: 7373210721dc
Create Date: 2025-07-05 18:45:52.590307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c400935a5708'
down_revision: Union[str, Sequence[str], None] = '7373210721dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas_electronicas', sa.Column('status_Getrequest', sa.Boolean(), nullable=True))
    op.add_column('facturas_electronicas', sa.Column('status_Postrequest', sa.Boolean(), nullable=True))
    op.add_column('facturas_electronicas', sa.Column('status_PDFrequest', sa.Boolean(), nullable=True))
    op.add_column('facturas_electronicas', sa.Column('pdfIO', sa.LargeBinary(), nullable=True))
    op.alter_column('facturas_electronicas', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('facturas_manuales', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas_manuales', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('facturas_electronicas', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('facturas_electronicas', 'pdfIO')
    op.drop_column('facturas_electronicas', 'status_PDFrequest')
    op.drop_column('facturas_electronicas', 'status_Postrequest')
    op.drop_column('facturas_electronicas', 'status_Getrequest')
    # ### end Alembic commands ###
