"""Crear tabla de usuarios

Revision ID: d39b42afb17e
Revises: 69f196f0c89a
Create Date: 2025-07-27 17:36:37.422300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39b42afb17e'
down_revision: Union[str, Sequence[str], None] = '69f196f0c89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('usuarios', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usuarios', 'is_active')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###
