"""Agregar columna fecha_creacion a facturas

Revision ID: e140444e4b50
Revises: 775eba70c541
Create Date: 2025-10-31 13:59:05.631207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e140444e4b50'
down_revision: Union[str, Sequence[str], None] = '775eba70c541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas_electronicas', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('facturas_manuales', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas_manuales', 'fecha_creacion')
    op.drop_column('facturas_electronicas', 'fecha_creacion')
    # ### end Alembic commands ###
