"""se actualizo nit_beneficiario en proyecto

Revision ID: e4784a95a3c9
Revises: 6af3b3ff712d
Create Date: 2025-09-23 15:31:04.477191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4784a95a3c9'
down_revision: Union[str, Sequence[str], None] = '6af3b3ff712d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('nit_beneficiario', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'nit_beneficiario')
    # ### end Alembic commands ###
