"""Agregar restriccion unique a url en factura electronica

Revision ID: f028f214a0e3
Revises: ad4c982d6b73
Create Date: 2025-08-13 15:02:14.616516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f028f214a0e3'
down_revision: Union[str, Sequence[str], None] = 'ad4c982d6b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_facturas_electronicas_url'), 'facturas_electronicas', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_electronicas_url'), table_name='facturas_electronicas')
    # ### end Alembic commands ###
